# Generated by Django 5.2.5 on 2025-09-02 01:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Encuesta',
                'verbose_name_plural': 'Tipos de Encuesta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('respondida', 'Respondida'), ('expirada', 'Expirada')], default='enviada', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('permite_respuesta_anonima', models.BooleanField(default=False)),
                ('token_acceso', models.CharField(editable=False, max_length=100, unique=True)),
                ('email_enviado', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to=settings.AUTH_USER_MODEL)),
                ('tipo_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='encuestas.tipoencuesta')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='EncuestaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_id', models.CharField(help_text='ID del servicio relacionado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_relacionado', to='encuestas.encuesta')),
            ],
            options={
                'verbose_name': 'Encuesta de Servicio',
                'verbose_name_plural': 'Encuestas de Servicio',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('tipo_pregunta', models.CharField(choices=[('texto', 'Texto Libre'), ('numero', 'Número'), ('escala', 'Escala (1-5)'), ('boolean', 'Sí/No'), ('multiple_choice', 'Opción Múltiple'), ('checkbox', 'Casillas de Verificación'), ('rating', 'Calificación con Estrellas')], max_length=20)),
                ('orden', models.IntegerField(default=1)),
                ('obligatoria', models.BooleanField(default=True)),
                ('opciones_json', models.JSONField(blank=True, help_text='Opciones para preguntas de opción múltiple o checkbox', null=True)),
                ('valor_minimo', models.IntegerField(blank=True, null=True)),
                ('valor_maximo', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='encuestas.encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['encuesta', 'orden'],
                'unique_together': {('encuesta', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_general', models.IntegerField(help_text='Calificación general del 1 al 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario_general', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('tiempo_respuesta_minutos', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_encuesta', to=settings.AUTH_USER_MODEL)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.encuesta')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuesta',
                'ordering': ['-fecha_respuesta'],
                'unique_together': {('encuesta', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='DetallePregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('respuesta_numero', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('respuesta_boolean', models.BooleanField(blank=True, null=True)),
                ('respuesta_escala', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('respuesta_multiple', models.JSONField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.pregunta')),
                ('respuesta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='encuestas.respuestaencuesta')),
            ],
            options={
                'verbose_name': 'Detalle de Pregunta',
                'verbose_name_plural': 'Detalles de Pregunta',
                'unique_together': {('respuesta_encuesta', 'pregunta')},
            },
        ),
        migrations.AddIndex(
            model_name='encuesta',
            index=models.Index(fields=['token_acceso'], name='encuestas_e_token_a_53b04d_idx'),
        ),
        migrations.AddIndex(
            model_name='encuesta',
            index=models.Index(fields=['cliente', 'estado'], name='encuestas_e_cliente_24455f_idx'),
        ),
    ]
