# Generated by Django 5.2.5 on 2025-12-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_pregunta_impacta_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('escala', 'Escala (1-10)')], default='texto', max_length=20),
        ),
    ]
