# Generated by GitHub Copilot on 2026-01-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encuestas", "0005_alter_pregunta_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encuesta",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="encuesta",
            name="fecha_creacion",
        ),
        migrations.AlterModelOptions(
            name="encuesta",
            options={
                "ordering": ["-id_encuesta"],
                "verbose_name": "Encuesta",
                "verbose_name_plural": "Encuestas",
            },
        ),
        migrations.RemoveIndex(
            model_name="pregunta",
            name="pregunta_encuest_006361_idx",
        ),
        migrations.RemoveField(
            model_name="pregunta",
            name="orden",
        ),
        migrations.AlterModelOptions(
            name="pregunta",
            options={
                "ordering": ["encuesta", "id_pregunta"],
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
            },
        ),
        migrations.RemoveField(
            model_name="encuestarespuesta",
            name="fecha_completada",
        ),
        migrations.RemoveField(
            model_name="encuestarespuesta",
            name="fecha_inicio",
        ),
        migrations.AddField(
            model_name="encuestarespuesta",
            name="fecha_realizacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="encuestarespuesta",
            options={
                "ordering": ["-id_encuesta_respuesta"],
                "verbose_name": "Encuesta Respondida",
                "verbose_name_plural": "Encuestas Respondidas",
            },
        ),
        migrations.RemoveField(
            model_name="respuesta",
            name="fecha_creacion",
        ),
        migrations.AlterModelOptions(
            name="respuesta",
            options={
                "ordering": ["encuesta_respuesta", "pregunta_id"],
                "verbose_name": "Respuesta",
                "verbose_name_plural": "Respuestas",
            },
        ),
    ]
