# Generated by Django 5.2.5 on 2025-09-02 01:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='solicitudes/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen de Solicitud',
                'verbose_name_plural': 'Imágenes de Solicitud',
                'ordering': ['fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ServicioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_planificada', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_utilizada', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto del Servicio',
                'verbose_name_plural': 'Productos del Servicio',
            },
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.CharField(editable=False, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de lo que necesita')),
                ('area_aproximada', models.DecimalField(blank=True, decimal_places=2, help_text='Área en metros cuadrados', max_digits=8, null=True)),
                ('presupuesto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('direccion_servicio', models.CharField(max_length=300)),
                ('ciudad_servicio', models.CharField(max_length=100)),
                ('provincia_servicio', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('en_diseño', 'En Diseño'), ('diseño_enviado', 'Diseño Enviado'), ('revision_diseño', 'En Revisión de Diseño'), ('aprobado', 'Diseño Aprobado'), ('rechazado', 'Diseño Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite_diseño', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones_cliente', models.TextField(blank=True, null=True)),
                ('observaciones_internas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Servicio',
                'verbose_name_plural': 'Solicitudes de Servicio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('diseño', 'Diseño'), ('construccion', 'Construcción'), ('consultoria', 'Consultoría')], max_length=20)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion_estimada_horas', models.IntegerField(help_text='Duración estimada en horas', validators=[django.core.validators.MinValueValidator(1)])),
                ('requiere_diseño', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ActualizacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso_anterior', models.IntegerField()),
                ('progreso_nuevo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen_progreso', models.ImageField(blank=True, null=True, upload_to='progreso_servicios/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones_servicio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actualización de Servicio',
                'verbose_name_plural': 'Actualizaciones de Servicio',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_servicio', models.CharField(default='Ejecutor', max_length=100)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('es_responsable', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(limit_choices_to={'groups__name__icontains': 'empleado'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_servicio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Empleado',
                'verbose_name_plural': 'Asignaciones de Empleados',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('vacaciones', 'Vacaciones'), ('licencia', 'Licencia'), ('baja_medica', 'Baja Médica')], default='disponible', max_length=20)),
                ('horas_disponibles', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(limit_choices_to={'groups__name__icontains': 'empleado'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad de Empleado',
                'verbose_name_plural': 'Disponibilidades de Empleados',
                'ordering': ['fecha', 'empleado__username'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaDiseño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion_diseño', models.TextField()),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_ejecucion_dias', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('archivo_diseño', models.FileField(blank=True, null=True, upload_to='diseños/')),
                ('imagen_renderizado', models.ImageField(blank=True, null=True, upload_to='renderizados/')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado al Cliente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('revision', 'En Revisión')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta_cliente', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comentarios_cliente', models.TextField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('diseñador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_diseño', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propuesta de Diseño',
                'verbose_name_plural': 'Propuestas de Diseño',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_servicio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('progreso_porcentaje', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones_ejecucion', models.TextField(blank=True, null=True)),
                ('observaciones_finalizacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
