# Generated by Django 5.2.5 on 2025-09-23 11:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_remove_producto_precio_compra_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('consultoria', 'Consultoría')], max_length=20)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion_estimada_horas', models.IntegerField(help_text='Duración estimada en horas', validators=[django.core.validators.MinValueValidator(1)])),
                ('requiere_diseño', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Diseño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tecnica', models.TextField(blank=True, help_text='Descripción técnica del diseño propuesto', null=True)),
                ('descripcion_deseada', models.TextField(blank=True, help_text='Descripción deseada por el cliente', null=True)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('diseñador_asignado', models.ForeignKey(blank=True, limit_choices_to={'perfil__tipo_usuario': 'diseñador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diseños_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diseño',
                'verbose_name_plural': 'Diseños',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenDiseño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='diseños/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('diseño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='servicios.diseño')),
                ('subida_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_diseño_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen de Diseño',
                'verbose_name_plural': 'Imágenes de Diseño',
                'ordering': ['fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_servicio', models.CharField(editable=False, max_length=20, unique=True)),
                ('notas_adicionales', models.TextField(blank=True, help_text='Notas adicionales del cliente', null=True)),
                ('direccion_servicio', models.CharField(max_length=300)),
                ('fecha_preferida', models.DateTimeField(help_text='Fecha preferida por el cliente')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Se establece cuando el diseño es aprobado', null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, help_text='Se establece cuando el servicio termina', null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('solicitud', 'Solicitud Inicial'), ('en_revision', 'En Revisión'), ('en_diseño', 'En Diseño'), ('diseño_enviado', 'Diseño Enviado'), ('revision_diseño', 'En Revisión de Diseño'), ('aprobado', 'Diseño Aprobado'), ('en_curso', 'En Ejecución'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('rechazado', 'Rechazado')], default='solicitud', max_length=20)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to=settings.AUTH_USER_MODEL)),
                ('pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicio', to='users.pago')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='servicios.tiposervicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='servicios/')),
                ('tipo_imagen', models.CharField(choices=[('jardin_actual', 'Imagen del Jardín Actual'), ('idea_referencia', 'Imagen de Idea/Referencia')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subida_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_servicio_subidas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Imagen de Servicio',
                'verbose_name_plural': 'Imágenes de Servicio',
                'ordering': ['fecha_subida'],
            },
        ),
        migrations.AddField(
            model_name='diseño',
            name='servicio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diseño', to='servicios.servicio'),
        ),
        migrations.CreateModel(
            name='AsignacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_servicio', models.CharField(default='Ejecutor', max_length=100)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('es_responsable', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(limit_choices_to={'perfil__tipo_usuario': 'empleado'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_servicio', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Asignación de Empleado',
                'verbose_name_plural': 'Asignaciones de Empleados',
            },
        ),
        migrations.CreateModel(
            name='ActualizacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso_anterior', models.IntegerField()),
                ('progreso_nuevo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen_progreso', models.ImageField(blank=True, null=True, upload_to='progreso_servicios/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones_servicio', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Actualización de Servicio',
                'verbose_name_plural': 'Actualizaciones de Servicio',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ServicioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_planificada', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_utilizada', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_utilizados', to='productos.producto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_utilizados', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Producto del Servicio',
                'verbose_name_plural': 'Productos del Servicio',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('vacaciones', 'Vacaciones'), ('licencia', 'Licencia'), ('baja_medica', 'Baja Médica')], default='disponible', max_length=20)),
                ('horas_disponibles', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(limit_choices_to={'groups__name__icontains': 'empleado'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad de Empleado',
                'verbose_name_plural': 'Disponibilidades de Empleados',
                'ordering': ['fecha', 'empleado__username'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
        migrations.AddIndex(
            model_name='diseño',
            index=models.Index(fields=['diseñador_asignado'], name='servicios_d_diseñad_e01a87_idx'),
        ),
        migrations.AddIndex(
            model_name='diseño',
            index=models.Index(fields=['servicio'], name='servicios_d_servici_b65953_idx'),
        ),
        migrations.AddIndex(
            model_name='diseño',
            index=models.Index(fields=['fecha_creacion'], name='servicios_d_fecha_c_2ce163_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionempleado',
            unique_together={('servicio', 'empleado')},
        ),
        migrations.AlterUniqueTogether(
            name='servicioproducto',
            unique_together={('servicio', 'producto')},
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['numero_servicio'], name='servicios_s_numero__f70866_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['cliente', 'estado'], name='servicios_s_cliente_90856b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['fecha_preferida'], name='servicios_s_fecha_p_7f1a79_idx'),
        ),
    ]
