# Generated by Django 5.2.5 on 2025-09-02 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_remove_producto_precio_compra_and_more'),
        ('servicios', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicio', to='users.pago'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='propuesta_aprobada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='servicios.propuestadiseño'),
        ),
        migrations.AddField(
            model_name='asignacionempleado',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='actualizacionservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='servicioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_utilizados', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='servicioproducto',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_utilizados', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_servicio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='diseñador_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name__icontains': 'diseñador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicio',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='servicios.solicitudservicio'),
        ),
        migrations.AddField(
            model_name='propuestadiseño',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='servicios.solicitudservicio'),
        ),
        migrations.AddField(
            model_name='imagensolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='servicios.solicitudservicio'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='servicios.tiposervicio'),
        ),
        migrations.AlterUniqueTogether(
            name='empleadodisponibilidad',
            unique_together={('empleado', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='asignacionempleado',
            unique_together={('servicio', 'empleado')},
        ),
        migrations.AlterUniqueTogether(
            name='servicioproducto',
            unique_together={('servicio', 'producto')},
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['numero_servicio'], name='servicios_s_numero__f70866_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['cliente', 'estado'], name='servicios_s_cliente_90856b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['fecha_programada'], name='servicios_s_fecha_p_a7c367_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propuestadiseño',
            unique_together={('solicitud', 'version')},
        ),
        migrations.AddIndex(
            model_name='solicitudservicio',
            index=models.Index(fields=['numero_solicitud'], name='servicios_s_numero__143d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudservicio',
            index=models.Index(fields=['cliente', 'estado'], name='servicios_s_cliente_64049b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudservicio',
            index=models.Index(fields=['diseñador_asignado'], name='servicios_s_diseñad_07f3ab_idx'),
        ),
    ]
