# Generated by Django 5.2.5 on 2025-10-17 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "__first__"),
        ("servicios", "0001_initial"),
        ("users", "0002_empleado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diseno",
            fields=[
                ("id_diseno", models.AutoField(primary_key=True, serialize=False)),
                (
                    "titulo",
                    models.CharField(help_text="Título del diseño", max_length=200),
                ),
                (
                    "descripcion",
                    models.TextField(help_text="Descripción detallada del diseño propuesto"),
                ),
                (
                    "presupuesto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Presupuesto total del diseño",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("presentado", "Presentado al cliente"),
                            ("aceptado", "Aceptado"),
                            ("rechazado", "Rechazado"),
                            ("revision", "En revisión"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_presentacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "observaciones_cliente",
                    models.TextField(
                        blank=True,
                        help_text="Comentarios del cliente sobre el diseño",
                        null=True,
                    ),
                ),
                (
                    "notas_internas",
                    models.TextField(blank=True, help_text="Notas internas del diseñador", null=True),
                ),
                (
                    "disenador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empleado/diseñador que creó el diseño",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disenos_creados",
                        to="users.empleado",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        help_text="Servicio al que pertenece este diseño",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disenos",
                        to="servicios.servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diseño",
                "verbose_name_plural": "Diseños",
                "db_table": "diseno",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DisenoProducto",
            fields=[
                (
                    "id_diseno_producto",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        default=1,
                        help_text="Cantidad del producto en el diseño",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio unitario del producto al momento de crear el diseño",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el uso del producto en el diseño",
                        null=True,
                    ),
                ),
                (
                    "diseno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="servicios.diseno",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disenos",
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto del Diseño",
                "verbose_name_plural": "Productos del Diseño",
                "db_table": "diseno_producto",
            },
        ),
        migrations.CreateModel(
            name="ImagenDiseno",
            fields=[
                (
                    "id_imagen_diseno",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "imagen",
                    models.ImageField(help_text="Imagen del diseño", upload_to="disenos/%Y/%m/"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        help_text="Descripción de la imagen",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "orden",
                    models.IntegerField(default=0, help_text="Orden de visualización de la imagen"),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "diseno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="servicios.diseno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de Diseño",
                "verbose_name_plural": "Imágenes de Diseño",
                "db_table": "imagen_diseno",
                "ordering": ["orden", "fecha_subida"],
            },
        ),
        migrations.AddIndex(
            model_name="diseno",
            index=models.Index(fields=["estado"], name="diseno_estado_108eb0_idx"),
        ),
        migrations.AddIndex(
            model_name="diseno",
            index=models.Index(fields=["servicio"], name="diseno_servici_19f44f_idx"),
        ),
        migrations.AddIndex(
            model_name="diseno",
            index=models.Index(fields=["fecha_creacion"], name="diseno_fecha_c_800111_idx"),
        ),
        migrations.AddIndex(
            model_name="disenoproducto",
            index=models.Index(fields=["diseno"], name="diseno_prod_diseno__5a1fea_idx"),
        ),
        migrations.AddIndex(
            model_name="disenoproducto",
            index=models.Index(fields=["producto"], name="diseno_prod_product_4c4609_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="disenoproducto",
            unique_together={("diseno", "producto")},
        ),
        migrations.AddIndex(
            model_name="imagendiseno",
            index=models.Index(fields=["diseno"], name="imagen_dise_diseno__2faf08_idx"),
        ),
        migrations.AddIndex(
            model_name="imagendiseno",
            index=models.Index(fields=["orden"], name="imagen_dise_orden_69ec0e_idx"),
        ),
    ]
