# Generated by Django 5.2.5 on 2025-10-17 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_reservaempleado_reserva_empleados'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='reserva',
            field=models.ForeignKey(blank=True, help_text='Reserva a la que pertenece este diseño', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disenos', to='servicios.reserva'),
        ),
    ]
