# Generated by Django 5.2.5 on 2025-10-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_imagenreserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='fecha_propuesta',
            field=models.DateField(blank=True, help_text='Fecha propuesta para realizar el servicio', null=True),
        ),
    ]
