# Generated by Django 5.2.5 on 2025-10-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_diseno_fecha_propuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseno',
            name='fecha_propuesta',
            field=models.DateTimeField(blank=True, help_text='Fecha propuesta para realizar el servicio', null=True),
        ),
    ]
