# Generated by Django 5.2.5 on 2025-11-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_reserva_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duracion_estimada',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo',
        ),
    ]
