# Generated by Django 5.2.5 on 2025-11-05 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0009_remove_servicio_duracion_estimada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="estado_pago",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobado", "Aprobado"),
                    ("rechazado", "Rechazado"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="fecha_pago",
            field=models.DateTimeField(blank=True, help_text="Fecha en que se completó el pago", null=True),
        ),
        migrations.AddField(
            model_name="reserva",
            name="mercadopago_payment_id",
            field=models.CharField(
                blank=True,
                help_text="ID de pago de MercadoPago",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="mercadopago_preference_id",
            field=models.CharField(
                blank=True,
                help_text="ID de preferencia de MercadoPago",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="mercadopago_status",
            field=models.CharField(
                blank=True,
                help_text="Estado del pago en MercadoPago",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="monto_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
