# Generated by Django 5.2.5 on 2025-11-05 11:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_reserva_estado_pago_reserva_fecha_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado_pago_final',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('sena_pagada', 'Seña Pagada'), ('pagado', 'Pagado Completamente'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado del pago final', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado_pago_sena',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('sena_pagada', 'Seña Pagada'), ('pagado', 'Pagado Completamente'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado del pago de seña', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_pago_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_pago_sena',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mercadopago_payment_id_final',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mercadopago_payment_id_sena',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mercadopago_preference_id_final',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mercadopago_preference_id_sena',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mercadopago_status_final',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mercadopago_status_sena',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto final a pagar (total - seña)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_sena',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto de seña para confirmar la reserva', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('sena_pagada', 'Seña Pagada'), ('pagado', 'Pagado Completamente'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mercadopago_preference_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mercadopago_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto total del servicio', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='ConfiguracionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_sena', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Monto de seña requerido para realizar una reserva', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('porcentaje_sena', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Porcentaje de seña sobre el total (0 para usar monto fijo)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Pago',
                'verbose_name_plural': 'Configuraciones de Pago',
                'db_table': 'configuracion_pago',
            },
        ),
    ]
