# Generated by Django 5.2.5 on 2025-11-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0011_sistema_pagos_dos_etapas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="fecha_pago",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="mercadopago_payment_id",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="mercadopago_payment_id_final",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="mercadopago_payment_id_sena",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="mercadopago_preference_id",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="mercadopago_preference_id_final",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="mercadopago_preference_id_sena",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="mercadopago_status",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="mercadopago_status_final",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="mercadopago_status_sena",
        ),
        migrations.AddField(
            model_name="reserva",
            name="payment_id_final",
            field=models.CharField(
                blank=True,
                help_text="ID de pago de MercadoPago para el pago final",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="payment_id_sena",
            field=models.CharField(
                blank=True,
                help_text="ID de pago de MercadoPago para la seña",
                max_length=200,
                null=True,
            ),
        ),
    ]
