# Generated by Django 5.2.5 on 2025-11-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_alter_reserva_estado_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='encuesta_token',
            field=models.UUIDField(blank=True, help_text='Token público para responder la encuesta de la reserva', null=True, unique=True),
        ),
    ]
