# Generated by Django 5.2.5 on 2025-11-29 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0017_reserva_fecha_realizacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormaTerreno",
            fields=[
                ("id_forma", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Forma de Terreno",
                "verbose_name_plural": "Formas de Terreno",
                "db_table": "forma_terreno",
            },
        ),
        migrations.CreateModel(
            name="Jardin",
            fields=[
                ("id_jardin", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ancho",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "largo",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "forma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jardines",
                        to="servicios.formaterreno",
                    ),
                ),
                (
                    "reserva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jardin",
                        to="servicios.reserva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jardín",
                "verbose_name_plural": "Jardines",
                "db_table": "jardin",
            },
        ),
        migrations.CreateModel(
            name="ZonaJardin",
            fields=[
                ("id_zona", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=120, null=True)),
                ("ancho", models.DecimalField(decimal_places=2, max_digits=8)),
                ("largo", models.DecimalField(decimal_places=2, max_digits=8)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "forma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zonas",
                        to="servicios.formaterreno",
                    ),
                ),
                (
                    "jardin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zonas",
                        to="servicios.jardin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zona de Jardín",
                "verbose_name_plural": "Zonas de Jardín",
                "db_table": "zona_jardin",
            },
        ),
        migrations.AddIndex(
            model_name="jardin",
            index=models.Index(fields=["reserva"], name="jardin_reserva_a06b1d_idx"),
        ),
        migrations.AddIndex(
            model_name="zonajardin",
            index=models.Index(fields=["jardin"], name="zona_jardin_jardin__b3bd56_idx"),
        ),
        migrations.AddIndex(
            model_name="zonajardin",
            index=models.Index(fields=["nombre"], name="zona_jardin_nombre_cd3f6b_idx"),
        ),
    ]
