# Generated by Django 5.2.5 on 2025-11-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0018_formaterreno_jardin_zonajardin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diseno",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Descripción detallada del diseño propuesto",
                null=True,
            ),
        ),
    ]
