# Generated by Django 5.2.5 on 2025-11-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0019_alter_diseno_descripcion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jardin",
            name="ancho",
        ),
        migrations.RemoveField(
            model_name="jardin",
            name="largo",
        ),
    ]
