# Generated by Django 5.2.5 on 2025-12-19 16:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0025_diseno_programacion_inicio_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaDiseno',
            fields=[
                ('id_tarea_diseno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('duracion_base', models.PositiveIntegerField(help_text='Duración (min)', validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_personal_minimo', models.PositiveIntegerField(help_text='Personal mínimo requerido', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Tarea de Diseño',
                'verbose_name_plural': 'Tareas de Diseño',
                'db_table': 'tarea_diseno',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DisenoTarea',
            fields=[
                ('id_diseno_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseno_tareas', to='servicios.diseno')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_disenos', to='servicios.tareadiseno')),
            ],
            options={
                'verbose_name': 'Diseño-Tarea',
                'verbose_name_plural': 'Diseños-Tareas',
                'db_table': 'diseno_tarea',
            },
        ),
        migrations.AddField(
            model_name='diseno',
            name='tareas_diseno',
            field=models.ManyToManyField(blank=True, related_name='disenos', through='servicios.DisenoTarea', to='servicios.tareadiseno'),
        ),
        migrations.AddIndex(
            model_name='disenotarea',
            index=models.Index(fields=['diseno'], name='diseno_tare_diseno__200593_idx'),
        ),
        migrations.AddIndex(
            model_name='disenotarea',
            index=models.Index(fields=['tarea'], name='diseno_tare_tarea_i_687d9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disenotarea',
            unique_together={('diseno', 'tarea')},
        ),
    ]
