# Generated by Django 5.2.5 on 2026-01-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0027_refactor_tareas_diseno_to_tarea'),
        ('users', '0008_rename_localidad_nombre__pais_idx_localidad_nombre__90332a_idx'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_cita'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveIndex(
            model_name='reserva',
            name='reserva_fecha_r_710b66_idx',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_reserva',
            new_name='fecha_cita',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_realizacion',
            new_name='fecha_finalizacion',
        ),
        migrations.RemoveField(
            model_name='configuracionpago',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='configuracionpago',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='configuracionpago',
            name='porcentaje_sena',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora real de inicio del servicio', null=True),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_cita'], name='reserva_fecha_c_4b0936_idx'),
        ),
    ]
