# Generated by GitHub Copilot on 2026-01-13

from django.db import migrations, models


OBJETIVOS = [
    ("bajo_mantenimiento", "Bajo Mantenimiento"),
    ("mucho_color", "Mucho Color"),
    ("selvatico", "Estilo Selvático"),
    ("minimalista", "Estilo Minimalista"),
    ("mascotas", "Espacio para Mascotas"),
    ("ninos", "Espacio para Niños"),
    ("huerta", "Huerta"),
    ("otro", "Otro"),
]


def forwards(apps, schema_editor):
    ObjetivoDiseno = apps.get_model("servicios", "ObjetivoDiseno")
    Reserva = apps.get_model("servicios", "Reserva")

    objetivos_by_codigo = {}
    for codigo, nombre in OBJETIVOS:
        obj, _created = ObjetivoDiseno.objects.get_or_create(
            codigo=codigo,
            defaults={"nombre": nombre, "activo": True},
        )
        # Si existía, aseguramos nombre/activo coherentes
        if obj.nombre != nombre or obj.activo is False:
            obj.nombre = nombre
            obj.activo = True
            obj.save(update_fields=["nombre", "activo"])
        objetivos_by_codigo[codigo] = obj

    # Migrar objetivo_diseno_legacy (string) -> objetivo_diseno (FK)
    # Migrar nivel_intervencion_legacy (string) -> nivel_intervencion (bool)
    for reserva in Reserva.objects.all().iterator():
        legacy_obj = getattr(reserva, "objetivo_diseno_legacy", None)
        if legacy_obj:
            objetivo = objetivos_by_codigo.get(legacy_obj)
            if objetivo is not None:
                reserva.objetivo_diseno_id = objetivo.id_objetivo_diseno

        legacy_nivel = getattr(reserva, "nivel_intervencion_legacy", None)
        if legacy_nivel is not None:
            if legacy_nivel == "desde_cero":
                reserva.nivel_intervencion = True
            elif legacy_nivel == "remodelacion":
                reserva.nivel_intervencion = False
            else:
                reserva.nivel_intervencion = None

        reserva.save(update_fields=["objetivo_diseno", "nivel_intervencion"])


def backwards(apps, schema_editor):
    # Best-effort reverse: restore legacy fields from FK/bool when possible.
    ObjetivoDiseno = apps.get_model("servicios", "ObjetivoDiseno")
    Reserva = apps.get_model("servicios", "Reserva")

    objetivos_by_id = {o.id_objetivo_diseno: o for o in ObjetivoDiseno.objects.all()}

    for reserva in Reserva.objects.all().iterator():
        objetivo_id = getattr(reserva, "objetivo_diseno_id", None)
        if objetivo_id:
            objetivo = objetivos_by_id.get(objetivo_id)
            if objetivo:
                reserva.objetivo_diseno_legacy = objetivo.codigo

        nivel = getattr(reserva, "nivel_intervencion", None)
        if nivel is True:
            reserva.nivel_intervencion_legacy = "desde_cero"
        elif nivel is False:
            reserva.nivel_intervencion_legacy = "remodelacion"
        else:
            reserva.nivel_intervencion_legacy = None

        reserva.save(update_fields=["objetivo_diseno_legacy", "nivel_intervencion_legacy"])


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0028_alter_reserva_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjetivoDiseno",
            fields=[
                ("id_objetivo_diseno", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Objetivo de Diseño",
                "verbose_name_plural": "Objetivos de Diseño",
                "db_table": "objetivo_diseno",
                "ordering": ["nombre"],
            },
        ),
        migrations.RenameField(
            model_name="reserva",
            old_name="objetivo_diseno",
            new_name="objetivo_diseno_legacy",
        ),
        migrations.AddField(
            model_name="reserva",
            name="objetivo_diseno",
            field=models.ForeignKey(
                blank=True,
                help_text="Objetivo principal del diseño",
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="reservas",
                to="servicios.objetivodiseno",
            ),
        ),
        migrations.RenameField(
            model_name="reserva",
            old_name="nivel_intervencion",
            new_name="nivel_intervencion_legacy",
        ),
        migrations.AddField(
            model_name="reserva",
            name="nivel_intervencion",
            field=models.BooleanField(
                blank=True,
                help_text="Nivel de intervención requerido (True=desde cero, False=remodelación)",
                null=True,
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="reserva",
            name="objetivo_diseno_legacy",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="nivel_intervencion_legacy",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="tipo_servicio_solicitado",
        ),
    ]
