# Generated by GitHub Copilot on 2026-01-13

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_pago_from_reserva(apps, schema_editor):
    Reserva = apps.get_model("servicios", "Reserva")
    Pago = apps.get_model("servicios", "Pago")

    db_alias = schema_editor.connection.alias

    reservas = Reserva.objects.using(db_alias).all().only(
        "id_reserva",
        "monto_sena",
        "estado_pago_sena",
        "payment_id_sena",
        "fecha_pago_sena",
        "monto_total",
        "estado_pago_final",
        "payment_id_final",
        "fecha_pago_final",
        "estado_pago",
    )

    for reserva in reservas.iterator():
        Pago.objects.using(db_alias).get_or_create(
            reserva_id=reserva.id_reserva,
            defaults={
                "monto_sena": reserva.monto_sena or Decimal("0"),
                "estado_pago_sena": reserva.estado_pago_sena or "pendiente",
                "payment_id_sena": reserva.payment_id_sena,
                "fecha_pago_sena": reserva.fecha_pago_sena,
                "monto_total": reserva.monto_total or Decimal("0"),
                "estado_pago_final": reserva.estado_pago_final or "pendiente",
                "payment_id_final": reserva.payment_id_final,
                "fecha_pago_final": reserva.fecha_pago_final,
                "estado_pago": reserva.estado_pago or "pendiente",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0029_objetivo_diseno_fk_y_nivel_intervencion_bool"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                ("id_pago", models.AutoField(primary_key=True, serialize=False)),
                (
                    "monto_sena",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Monto de seña para confirmar la reserva",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "estado_pago_sena",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pendiente_pago_sena", "Pendiente de Pago de Seña"),
                            ("sena_pagada", "Seña Pagada"),
                            ("pagado", "Pagado Completamente"),
                            ("rechazado", "Rechazado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        help_text="Estado del pago de seña",
                        max_length=20,
                    ),
                ),
                (
                    "payment_id_sena",
                    models.CharField(
                        blank=True,
                        help_text="ID de pago de MercadoPago para la seña",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("fecha_pago_sena", models.DateTimeField(blank=True, null=True)),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Monto total del servicio (sin descontar la seña)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "estado_pago_final",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pendiente_pago_sena", "Pendiente de Pago de Seña"),
                            ("sena_pagada", "Seña Pagada"),
                            ("pagado", "Pagado Completamente"),
                            ("rechazado", "Rechazado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        help_text="Estado del pago final",
                        max_length=20,
                    ),
                ),
                (
                    "payment_id_final",
                    models.CharField(
                        blank=True,
                        help_text="ID de pago de MercadoPago para el pago final",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("fecha_pago_final", models.DateTimeField(blank=True, null=True)),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pendiente_pago_sena", "Pendiente de Pago de Seña"),
                            ("sena_pagada", "Seña Pagada"),
                            ("pagado", "Pagado Completamente"),
                            ("rechazado", "Rechazado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "reserva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pago",
                        to="servicios.reserva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "pago_reserva",
            },
        ),
        migrations.RunPython(backfill_pago_from_reserva, migrations.RunPython.noop),
        migrations.RemoveField(model_name="reserva", name="monto_sena"),
        migrations.RemoveField(model_name="reserva", name="estado_pago_sena"),
        migrations.RemoveField(model_name="reserva", name="payment_id_sena"),
        migrations.RemoveField(model_name="reserva", name="fecha_pago_sena"),
        migrations.RemoveField(model_name="reserva", name="monto_total"),
        migrations.RemoveField(model_name="reserva", name="monto_final"),
        migrations.RemoveField(model_name="reserva", name="estado_pago_final"),
        migrations.RemoveField(model_name="reserva", name="payment_id_final"),
        migrations.RemoveField(model_name="reserva", name="fecha_pago_final"),
        migrations.RemoveField(model_name="reserva", name="estado_pago"),
    ]
