# Generated by GitHub Copilot on 2026-01-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0030_pagos_a_tabla_pago"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="imagenzona",
            name="imagen_zona_orden_449c99_idx",
        ),
        migrations.RemoveField(
            model_name="imagenzona",
            name="orden",
        ),
        migrations.RemoveField(
            model_name="imagenzona",
            name="fecha_subida",
        ),
        migrations.RemoveField(
            model_name="jardin",
            name="fecha_creacion",
        ),
        migrations.RemoveField(
            model_name="jardin",
            name="fecha_actualizacion",
        ),
    ]
