# Generated by Django 5.2.5 on 2026-01-27 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0031_remove_jardin_fechas_imagenzona_orden_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='disenotarea',
            name='cantidad',
            field=models.IntegerField(default=1, help_text='Cantidad de veces que se repite la tarea en el diseño', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
