# Generated by Django 5.2.5 on 2026-01-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0032_add_cantidad_diseno_tarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="fecha_realizacion",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text=(
                    "Fecha y hora planificada para realizar el servicio (según propuesta de diseño aceptada)"
                ),
            ),
        ),
    ]
