# Generated by GitHub Copilot on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0033_reserva_fecha_realizacion_programada"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionpago",
            name="notificaciones_activas",
            field=models.BooleanField(
                default=True,
                help_text="Activa o desactiva notificaciones internas por email",
            ),
        ),
    ]
