# Generated by GitHub Copilot on 2026-02-08

from django.db import migrations, models


def seed_catalogos(apps, schema_editor):
    OpcionNivelIntervencion = apps.get_model("servicios", "OpcionNivelIntervencion")
    OpcionPresupuestoAproximado = apps.get_model("servicios", "OpcionPresupuestoAproximado")

    if not OpcionNivelIntervencion.objects.exists():
        OpcionNivelIntervencion.objects.bulk_create(
            [
                OpcionNivelIntervencion(
                    codigo="remodelacion",
                    nombre="Remodelación Parcial",
                    valor=False,
                    activo=True,
                    orden=1,
                ),
                OpcionNivelIntervencion(
                    codigo="desde_cero",
                    nombre="Diseño Completo desde Cero",
                    valor=True,
                    activo=True,
                    orden=2,
                ),
            ]
        )

    if not OpcionPresupuestoAproximado.objects.exists():
        OpcionPresupuestoAproximado.objects.bulk_create(
            [
                OpcionPresupuestoAproximado(
                    codigo="bajo",
                    nombre="Económico / Ajustado",
                    activo=True,
                    orden=1,
                ),
                OpcionPresupuestoAproximado(
                    codigo="medio",
                    nombre="Intermedio / Flexible",
                    activo=True,
                    orden=2,
                ),
                OpcionPresupuestoAproximado(
                    codigo="alto",
                    nombre="Premium / Sin Restricciones",
                    activo=True,
                    orden=3,
                ),
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0034_configuracionpago_notificaciones_activas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracionpago",
            name="notificaciones_activas",
        ),
        migrations.CreateModel(
            name="OpcionNivelIntervencion",
            fields=[
                ("id_opcion_nivel", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("valor", models.BooleanField(help_text="True=desde cero, False=remodelación")),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Opción de Nivel de Intervención",
                "verbose_name_plural": "Opciones de Nivel de Intervención",
                "db_table": "opcion_nivel_intervencion",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="OpcionPresupuestoAproximado",
            fields=[
                ("id_opcion_presupuesto", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Opción de Presupuesto Aproximado",
                "verbose_name_plural": "Opciones de Presupuesto Aproximado",
                "db_table": "opcion_presupuesto_aproximado",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.AlterField(
            model_name="reserva",
            name="presupuesto_aproximado",
            field=models.CharField(
                blank=True,
                help_text="Rango de presupuesto estimado por el cliente",
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(seed_catalogos, migrations.RunPython.noop),
    ]
