# Generated by Django 5.2.5 on 2025-11-14 00:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0014_reserva_encuesta_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('precipitation_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precipitation_probability', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('open-meteo', 'Open-Meteo'), ('smn', 'Servicio Meteorológico Nacional'), ('other', 'Otro')], default='open-meteo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pronóstico meteorológico',
                'verbose_name_plural': 'Pronósticos meteorológicos',
                'db_table': 'weather_forecast',
                'ordering': ['-date'],
                'unique_together': {('date', 'latitude', 'longitude', 'source')},
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField()),
                ('alert_type', models.CharField(choices=[('rain', 'Lluvia'), ('storm', 'Tormenta')], default='rain', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('precipitation_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precipitation_threshold', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('probability_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('is_simulated', models.BooleanField(default=False)),
                ('requires_reprogramming', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('acknowledged', 'En revisión'), ('resolved', 'Resuelta')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='open-meteo', max_length=20)),
                ('triggered_by', models.CharField(blank=True, max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_generadas', to='weather.weatherforecast')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_clima', to='servicios.reserva')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_alerts_resueltas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_clima', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Alerta climática',
                'verbose_name_plural': 'Alertas climáticas',
                'db_table': 'weather_alert',
                'ordering': ['status', 'alert_date'],
            },
        ),
    ]
