# Generated by Django 5.2.5 on 2025-09-02 01:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('productos', '0002_remove_producto_precio_compra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('mercado_pago', 'Mercado Pago'), ('paypal', 'PayPal'), ('crypto', 'Criptomoneda'), ('vale', 'Vale/Cupón'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('comision_fija', models.DecimalField(decimal_places=2, default=0, help_text='Comisión fija por transacción', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro'), ('auto', 'Automático')], default='claro', max_length=20)),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=10)),
                ('zona_horaria', models.CharField(default='America/Argentina/Buenos_Aires', max_length=50)),
                ('notif_stock_bajo', models.BooleanField(default=True)),
                ('notif_nuevos_productos', models.BooleanField(default=False)),
                ('notif_cambios_precios', models.BooleanField(default=False)),
                ('productos_por_pagina', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(1)])),
                ('mostrar_precios_compra', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transaccion', models.CharField(editable=False, max_length=50, unique=True)),
                ('tipo_transaccion', models.CharField(choices=[('servicio', 'Pago de Servicio'), ('diseño', 'Pago de Diseño'), ('devolucion', 'Devolución'), ('reembolso', 'Reembolso'), ('ajuste', 'Ajuste'), ('comision', 'Comisión'), ('otro', 'Otro')], default='servicio', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_comision', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_neto', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='users.metodopago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pago', to='productos.producto')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pago', to='users.pago')),
            ],
            options={
                'verbose_name': 'Detalle de Pago',
                'verbose_name_plural': 'Detalles de Pago',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, null=True)),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('cuit', 'CUIT'), ('cuil', 'CUIL'), ('pasaporte', 'Pasaporte'), ('cedula', 'Cédula')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')])),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')])),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(default='Argentina', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['numero_documento'], name='users_perso_numero__392600_idx'), models.Index(fields=['apellidos', 'nombres'], name='users_perso_apellid_f9334a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('diseñador', 'Diseñador'), ('administrador', 'Administrador')], default='cliente', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('bloqueado', 'Bloqueado')], default='activo', max_length=20)),
                ('debe_cambiar_password', models.BooleanField(default=False)),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos_login', models.IntegerField(default=0)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('recibir_notificaciones_email', models.BooleanField(default=True)),
                ('recibir_notificaciones_sistema', models.BooleanField(default=True)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(help_text='Información personal del usuario', on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_usuario', to='users.persona')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['persona__apellidos', 'persona__nombres'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('permisos_especiales', models.JSONField(blank=True, default=dict)),
                ('nivel_acceso', models.IntegerField(default=1, help_text='Nivel de acceso (1=básico, 10=administrador)', validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol_extendido', to='auth.group')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nivel_acceso', 'grupo__name'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(blank=True, max_length=100, null=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Acceso',
                'verbose_name_plural': 'Historiales de Acceso',
                'ordering': ['-fecha_acceso'],
                'indexes': [models.Index(fields=['user', 'fecha_acceso'], name='users_histo_user_id_bc23ad_idx'), models.Index(fields=['ip_address'], name='users_histo_ip_addr_a596d3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['numero_transaccion'], name='users_pago_numero__3b855c_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['user', 'fecha_pago'], name='users_pago_user_id_9884fa_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado'], name='users_pago_estado_6933aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallepago',
            unique_together={('pago', 'producto')},
        ),
    ]
