# Generated by Django 5.2.5 on 2025-10-15 23:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'db_table': 'genero',
                'ordering': ['genero'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipo_documento',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('cp', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('nombre_localidad', models.CharField(max_length=100)),
                ('nombre_provincia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidad',
                'ordering': ['nombre_provincia', 'nombre_localidad'],
                'indexes': [models.Index(fields=['cp'], name='localidad_cp_7472d8_idx'), models.Index(fields=['nombre_provincia'], name='localidad_nombre__322201_idx')],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')])),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('dpto', models.CharField(blank=True, max_length=10, null=True)),
                ('nro_documento', models.CharField(max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='users.genero')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='users.localidad')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='users.tipodocumento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='users.persona')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=13, unique=True)),
                ('nombre_contacto', models.CharField(help_text='Nombre de la persona de contacto', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(help_text='Dirección completa del proveedor', max_length=300)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['cuit'], name='proveedor_cuit_5d9233_idx'), models.Index(fields=['razon_social'], name='proveedor_razon_s_b521be_idx'), models.Index(fields=['email'], name='proveedor_email_9a716e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['nro_documento'], name='persona_nro_doc_5d734a_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['email'], name='persona_email_32098e_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['apellido', 'nombre'], name='persona_apellid_396e59_idx'),
        ),
    ]
