# Generated by Django 5.2.5 on 2025-09-02 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='producto',
            name='cuidados_especiales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='epoca_siembra',
            field=models.CharField(blank=True, help_text='Época recomendada de siembra', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_perecedero',
            field=models.BooleanField(default=False, help_text='Indica si el producto es perecedero'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Precio que se cobra al cliente en servicios', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de costo del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='requiere_refrigeracion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('planta', 'Planta'), ('semilla', 'Semilla'), ('fertilizante', 'Fertilizante'), ('herramienta', 'Herramienta'), ('equipo', 'Equipo'), ('decoracion', 'Decoración'), ('sustrato', 'Sustrato'), ('maceta', 'Maceta'), ('sistema_riego', 'Sistema de Riego'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tipo_producto'], name='productos_p_tipo_pr_74920b_idx'),
        ),
    ]
