# Generated by Django 5.2.5 on 2025-12-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_especie_y_tipo_producto'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='producto',
            new_name='producto_especie_4e35bf_idx',
            old_name='producto_especie_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='producto_tipoPro_0ae95b_idx',
            old_name='producto_tipo_producto_idx',
        ),
    ]
