# Generated by Django 5.2.5 on 2026-01-12 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_merge_0003_rename_indices_0003_tareas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='cantidad_personal_minimo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='duracion_base',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
