# Generated by Django 5.2.5 on 2026-01-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_tarea_cantidad_personal_minimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='cantidad_minima',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fecha_actualizacion',
        ),
    ]
