# Generated by Django 5.2.5 on 2026-05-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_soft_delete_catalogos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='producto',
            new_name='producto_activo_63f8df_idx',
            old_name='producto_activo_idx',
        ),
    ]
