# Generated by GitHub Copilot on 2026-01-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "audit",
            "0002_rename_audit_log_created_idx_audit_log_created_5a7975_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="endpoint",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user_agent",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="payload",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="response_code",
        ),
    ]
