# Generated by GitHub Copilot on 2026-01-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_remove_auditlog_request_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="role",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
