# Generated by Django 5.2.5 on 2026-05-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='emails_noti_recipie_72e6df_idx',
            old_name='emails_noti_recipie_9d2b7f_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='emails_noti_read_at_5500f6_idx',
            old_name='emails_noti_read_at_3750cf_idx',
        ),
    ]
